line-length = 88
target-version = "py310"

[lint]
select = ["E", "F", "I"]
ignore = []

[lint.per-file-ignores]
"nix/nodes/common/services/python-microservices/template.py" = ["F821", "E402", "F401"]
"bin/ai/face_detection_streamlit.py" = ["E402"]
