[workspaces]
www = 1
calendar = 2

meta_ai_claude = 1500
meta_ai_jules = 1501

meta_dbeaver = 1600

meta_steam = 1700


meta_keepass = 1801
meta_obsidian = 1802
meta_fava_beancount = 1803
meta_dotfiles = 1804
meta_super_productivity = 1805

comm_telegram = 1900
comm_element = 1901
comm_whatsapp = 1902
comm_meet = 1903
comm_discord_profissional = 1904
comm_discord_pessoal = 1905
comm_discord_video = 1906

work_lewtec = 2000
work_lewtec_vps = 2001
work_lewtec_contapila = 2003
work_lewtec_romaneiro = 2004
work_lewtec_launcher = 2005
work_lewtec_homepage = 2006
work_lewtec_infra = 2007

work_mestrado = 2200

side_blog = 3000
side_nixpkgs = 3002
side_contapila = 3004
side_rinha_backend = 3005
side_curso_latex = 3006
side_uilab = 3007
side_miseci = 3008
side_fetchurl = 3009

stat_riverwood = 4000
stat_whiterun = 4001
stat_ravenrock = 4002
stat_dgxa100 = 4003

video_obs_live = 8000

waypipe = 9999

[editor]
default = "hx"

[modules.fontconfig]
enable = true
serif = "Fira Code"
sans_serif = "Fira Code"
monospace = "Fira Code"
emoji = "Noto Color Emoji"

[desktop.wallpaper]
dir = "~/.dotfiles/assets"
default = "wall.jpg"

[backup]
rsyncnet_user = "de3163@de3163.rsync.net"

[hosts.riverwood]
tailscale_ip = "100.82.35.120"
zerotier_ip = "192.168.69.2"
port = 22

[hosts.whiterun]
tailscale_ip = "100.85.38.19"
zerotier_ip = "192.168.69.1"
mac = "a8:a1:59:9c:ab:32"
port = 22

[hosts.ravenrock]
tailscale_ip = "100.122.87.59"
port = 22

[hosts.phone]
tailscale_ip = "100.76.88.29"
zerotier_ip = "192.168.69.4"
port = 22

[browser]
default = "zen"
webapp = "brave"

[modules.webapp]
enable = true

[modules.base16]
enable = true
base00 = "282c34"
base01 = "353b45"
base02 = "3e4451"
base03 = "545862"
base04 = "565c64"
base05 = "abb2bf"
base06 = "b6bdca"
base07 = "c8ccd4"
base08 = "e06c75"
base09 = "d19a66"
base0A = "e5c07b"
base0B = "98c379"
base0C = "56b6c2"
base0D = "61afef"
base0E = "c678dd"
base0F = "be5046"

[modules.base16-shell]
enable = true

[modules.base16-helix]
enable = true

[modules.base16-vscode]
enable = true

[modules.base16-sway]
enable = true

[modules.script-directory]
enable = true

[modules.webapp.apps.castable-iframe]
url = "https://castable-iframe.vercel.app/"
profile = "castable-iframe"

[modules.webapp.apps.gemini]
url = "https://gemini.google.com"

[modules.webapp.apps.teste]
url = "https://google.com"

[modules.webapp.apps.element]
url = "https://app.element.io"
profile = "element"
desktop_name = "Element Matrix"

[modules.webapp.apps.reemo]
url = "https://reemo.io"
desktop_name = "Remote control"

[modules.webapp.apps.clickup]
url = "https://clickup.com"
desktop_name = "ClickUp"

[modules.webapp.apps.facebook]
url = "https://facebook.com"
profile = "facebook"
desktop_name = "Facebook"

[modules.webapp.apps.pocketcasts]
url = "https://pocketcasts.com"
desktop_name = "PocketCasts"
icon = "sound"

[modules.webapp.apps.twitter]
url = "https://twitter.com"
profile = "twitter"
desktop_name = "Twitter"

[modules.webapp.apps.discord-pessoal]
url = "https://discord.com/channels/me"
profile = "discord-pessoal"
desktop_name = "Discord (pessoal)"

[modules.webapp.apps.discord-profissional]
url = "https://discord.com/channels/me"
profile = "discord-profissional"
desktop_name = "Discord (profissional)"

[modules.webapp.apps.youtube-tv]
url = "https://youtube.com/tv"
profile = "youtube-tv"
desktop_name = "YouTube (UI para TV)"

[modules.webapp.apps.whatsapp]
url = "web.whatsapp.com"
profile = "zap"
desktop_name = "WhatsApp"

[modules.webapp.apps.notion]
url = "notion.so"
profile = "notion"
desktop_name = "Notion"

[modules.webapp.apps.duolingo]
url = "duolingo.com"
desktop_name = "Duolingo"

[modules.webapp.apps.youtube-music]
url = "music.youtube.com"
profile = "youtubemusic"
desktop_name = "Youtube Music"

[modules.webapp.apps.planttext]
url = "https://www.planttext.com/"
desktop_name = "PlantText"

[modules.webapp.apps.rainmode]
url = "https://youtu.be/mPZkdNFkNps"
desktop_name = "Tocar som de chuva"
icon = "weather-showers"

[modules.webapp.apps.gmail]
url = "gmail.com"
desktop_name = "GMail"

[modules.webapp.apps.keymash]
url = "https://keyma.sh/learn"
desktop_name = "keyma.sh: Keyboard typing train"

[modules.webapp.apps.calendar]
url = "https://calendar.google.com/calendar/u/0/r/customday"
desktop_name = "Calend√°rio"
icon = "x-office-calendar"

[modules.webapp.apps.twitch-dashboard]
url = "https://dashboard.twitch.tv/stream-manager"

[modules.webapp.apps.trello-pessoal]
url = "https://trello.com/b/bjoRKSM2/pessoal"

[modules.webapp.apps.trello-side-projects]
url = "https://trello.com/b/36ncJYYV/side-projects"

[modules.webapp.apps.trello-dashboard]
url = "trello.com"

[modules.webapp.apps.geforce-now]
url = "play.geforcenow.com"

[modules.webapp.apps.deezer]
url = "deezer.com"

[modules.webapp.apps.jules]
url = "jules.google.com"

[modules.webapp.apps.claude-code-web]
url = "claude.ai/code"

[lazy_tools."github:zed-industries/zed"]
version = "0.222.4"
bins = ["zed"]

[lazy_tools."bun"]
version = "1.3.8"

[lazy_tools."docker-compose"]
version = "5.0.1"
global = true

[lazy_tools."fd"]
version = "10.3.0"
global = true

[lazy_tools."opencode"]
version = "1.1.40"
global = true

[lazy_tools."rclone"]
version = "1.72.1"
global = true

[lazy_tools."ripgrep"]
version = "15.1.0"
global = true
bins = ["rg"]

[lazy_tools."fzf"]
version = "0.67.0"
global = true
bins = ["fzf", "fzf-tmux"]

[lazy_tools."ruff"]
version = "0.14.14"

[lazy_tools."shfmt"]
version = "3.12.0"

[lazy_tools."shellcheck"]
version = "0.11.0"

[lazy_tools."sops"]
version = "3.11.0"

[lazy_tools."uv"]
version = "0.9.28"
global = true

[lazy_tools."yt-dlp"]
version = "2025.10.22"
global = true

[lazy_tools."terraform"]
version = "1.9.0"

[lazy_tools."tflint"]
version = "0.60.0"

[lazy_tools."go"]
version = "1.24.12"
bins = ["go", "gofmt"]

[lazy_tools."golangci-lint"]
version = "1.61.0"

[lazy_tools."github:docker/docker-language-server"]
version = "0.20.1"
global = true
bins = ["docker-langserver"]

[lazy_tools."github:ffbinaries/ffbinaries-prebuilt"]
version = "6.1"
bins = ["ffmpeg", "ffprobe"]

[lazy_tools."github:helix-editor/helix"]
version = "25.07.1"
global = true
bins = ["hx"]

[lazy_tools."github:valentjn/ltex-ls"]
version = "16.0.0"
global = true

[lazy_tools."npm:bash-language-server"]
version = "5.6.0"
global = true

[lazy_tools."npm:vscode-langservers-extracted"]
version = "4.10.0"
bins = ["vscode-html-language-server", "vscode-css-language-server", "vscode-json-language-server", "vscode-eslint-language-server"]

[lazy_tools."vfox:clang"]
version = "18.1.8"
bins = ["clang", "clang++"]

[lazy_tools."jless"]
version = "0.9.0"
global = true

[lazy_tools."gh"]
version = "2.86.0"
global = true

[drivers."workspaced/pkg/driver/terminal.Driver"]
terminal_kitty = 100

[desktop]
dark_mode = true

[desktop.raw.dconf."org/gnome/desktop/background"]
picture-options = "zoom"
primary-color = "#ffffff"
secondary-color = "#000000"

[desktop.raw.dconf."org/gnome/desktop/input-sources"]
current = "uint32 0"
xkb-options = ["terminate:ctrl_alt_bksp"]

[desktop.raw.dconf."org/gnome/desktop/peripherals/keyboard"]
numlock-state = false

[desktop.raw.dconf."org/gnome/desktop/privacy"]
disable-microphone = true
report-technical-problems = false

[desktop.raw.dconf."org/gnome/system/location"]
enabled = false

[desktop.raw.dconf."org/gnome/desktop/periphereals/touchpad"]
tap-to-click = true

