# Note for agents: if anything here is using a specific version make sure to pin it
# version = latest is not acceptable in this file
# use "mise use --pin" to pin a tool

[tools]
node = "25.5.0"
bun = "1.3.5"
docker-compose = "5.0.1"
fd = "10.3.0"
"github:anomalyco/opencode" = "1.1.16"
"github:docker/docker-language-server" = "0.20.1"
"github:ffbinaries/ffbinaries-prebuilt" = "6.1"
"github:helix-editor/helix" = "25.07.1"
"github:lewtec/rotulador" = "0.2.2"
"github:valentjn/ltex-ls" = "16.0.0"
"npm:bash-language-server" = "5.6.0"
"npm:vscode-langservers-extracted" = "4.10.0"
rclone = "1.72.1"
ripgrep = "15.1.0"
ruff = "0.14.0"
sops = "3.11.0"
uv = "0.9.18"
"vfox:clang" = "18.1.8"
yt-dlp = "2025.10.22"
