# Note for agents: if anything here is using a specific version make sure to pin it
# version = latest is not acceptable in this file
# use "mise use --pin" to pin a tool

[tools]
"aqua:nodejs/node" = "25.2.1"
"github:docker/docker-language-server" = "0.20.1"
"github:lewtec/rotulador" = "0.2.2"
"npm:bash-language-server" = "5.6.0"
"npm:vscode-langservers-extracted" = "4.10.0"
