[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
bun = true

[tools]
aqua = "latest"
"github:bytecodealliance/javy" = "latest"
"github:lewtec/rotulador" = "0.2.2"
"github:lucasew/go-annotation" = "latest"
"github:lucasew/redial_proxy" = "latest"
"github:lucasew/simple-dashboard" = "latest"
"github:lucasew/ts-proxy" = "latest"
usage = "latest"
